sysmo: vty: Add missing include for lchan_deactivate
Fixes following compilation warning:
osmo-bts/src/osmo-bts-sysmo/sysmobts_vty.c:349:3: warning: implicit declaration of function ‘lchan_deactivate’

Change-Id: I1dba0b08fdb2af199f009842c9abf32e25f74be1