bts-trx: Set max TRXD buf size to UINT16_MAX
Otherwise trying to allocate a msgb from it fails:
"""
In file included from /git/osmo-bts/src/osmo-bts-trx/l1_if.h:9,
                 from /git/osmo-bts/src/osmo-bts-trx/trx_if.c:50:
/git/osmo-bts/src/osmo-bts-trx/trx_if.c: In function ‘trx_if_send_burst’:
/git/osmo-bts/src/osmo-bts-trx/trx_if.h:6:33: error: unsigned conversion from ‘int’ to ‘uint16_t’ {aka ‘short unsigned int’} changes value from
65536’ to ‘0’ [-Werror=overflow]
    6 | #define TRXD_MSG_BUF_SIZE       65536
      |                                 ^~~~~
/git/osmo-bts/src/osmo-bts-trx/trx_if.c:1126:48: note: in expansion of macro ‘TRXD_MSG_BUF_SIZE’
 1126 |                 trx_data_last_msg = msgb_alloc(TRXD_MSG_BUF_SIZE, "tx_trxd");
      |                                                ^~~~~~~~~~~~~~~~~
"""

Simply set it to be within uint16_t range, since anyway IPv4 MTU (IP
Total Length field) is 16 bit (value including the IP header length too).

In any case, this will need to be trimmed further.

Change-Id: I980faea05dee405c974636f41ee723659d9c5229